[package]
name = "llmpeg"
version = "0.1.1"
edition = "2021"

[dependencies]
allms = "0.16.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11.6"
genai = "0.1.23"
exitcode = "1.1.2"
